const products=[
{id:1,name:"Everyday Runner",category:"shoes",type:"Sneakers",tag:"BESTSELLER",price:88,image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85",alt:"Red and white statement sneaker",colors:["#d44b3e","#e9e5d9","#252622"]},
{id:2,name:"Studio Overshirt",category:"clothing",type:"Outerwear",tag:"NEW",price:96,image:"https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=85",alt:"Neutral overshirt",colors:["#c8b8a2","#55594a","#262723"]},
{id:3,name:"Court Classic",category:"shoes",type:"Low-top sneakers",tag:"EVERYDAY",price:74,image:"https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=85",alt:"Minimal white sneakers",colors:["#e7e3d9","#242521"]},
{id:4,name:"Relaxed Knit",category:"clothing",type:"Knitwear",tag:"",price:82,image:"https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=85",alt:"Neutral knitwear",colors:["#d6c8b7","#696b5e"]},
{id:5,name:"Weekend High-top",category:"shoes",type:"High-top sneakers",tag:"LIMITED",price:112,image:"https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=85",alt:"Modern high-top sneaker",colors:["#e8e4db","#777d6b","#292a26"]},
{id:6,name:"Daily Utility Pant",category:"clothing",type:"Trousers",tag:"",price:78,image:"https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85",alt:"Everyday streetwear outfit",colors:["#a5a18d","#292a26"]},
{id:7,name:"Trail Form",category:"shoes",type:"Utility sneakers",tag:"NEW",price:124,image:"https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=900&q=85",alt:"Contemporary athletic sneaker",colors:["#d2c7b4","#51564a"]},
{id:8,name:"Heavyweight Tee",category:"clothing",type:"T-shirts",tag:"CORE PIECE",price:38,image:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85",alt:"Neutral t-shirt",colors:["#e9e5dc","#8d8d7e","#272823"]}
];
const state={category:"all",search:"",sort:"featured",cart:[],favorites:new Set()};
const $=id=>document.getElementById(id);let toastTimer;
const money=n=>new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(n);
function listProducts(){let list=products.filter(p=>(state.category==="all"||p.category===state.category)&&(p.name.toLowerCase().includes(state.search)||p.type.toLowerCase().includes(state.search)));if(state.sort==="low")list.sort((a,b)=>a.price-b.price);if(state.sort==="high")list.sort((a,b)=>b.price-a.price);if(state.sort==="name")list.sort((a,b)=>a.name.localeCompare(b.name));return list}
function renderProducts(){const list=listProducts();$("products").innerHTML=list.map((p,i)=>`<article class="card" style="animation-delay:${i*30}ms"><div class="product-image"><img src="${p.image}" alt="${p.alt}" loading="lazy">${p.tag?`<span class="badge">${p.tag}</span>`:""}<button class="heart ${state.favorites.has(p.id)?"fav":""}" data-fav="${p.id}" aria-label="Toggle favourite" aria-pressed="${state.favorites.has(p.id)}">${state.favorites.has(p.id)?"♥":"♡"}</button></div><div class="product-meta"><div><h3 class="product-name">${p.name}</h3><p class="product-type">${p.type}</p></div><span class="price">${money(p.price)}</span></div><div class="product-bottom"><div class="dots">${p.colors.map(c=>`<span class="dot" style="background:${c}"></span>`).join("")}</div><button class="add" data-add="${p.id}">Add to bag <span>↗</span></button></div></article>`).join("");$("products").hidden=!list.length;$("empty").hidden=!!list.length;$("result-count").textContent=list.length===products.length?`Showing ${list.length} considered essentials`:`Showing ${list.length} of ${products.length} pieces`}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").classList.remove("show"),2300)}
function add(id){const item=state.cart.find(x=>x.id===id);if(item)item.qty++;else state.cart.push({id,qty:1});renderCart();toast(`${products.find(p=>p.id===id).name} added to your bag.`)}
function renderCart(){const qty=state.cart.reduce((n,x)=>n+x.qty,0);$("cart-count").textContent=qty;$("drawer-count").textContent=`(${qty})`;$("cart-empty").hidden=qty>0;$("cart-items").hidden=!qty;$("cart-summary").hidden=!qty;$("cart-items").innerHTML=state.cart.map(x=>{const p=products.find(y=>y.id===x.id);return `<div class="cart-line"><img src="${p.image}" alt="${p.alt}"><div><h3>${p.name}</h3><p>${p.type}</p><div class="qty"><button data-qty="${p.id}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${x.qty}</span><button data-qty="${p.id}" data-delta="1" aria-label="Increase quantity">+</button></div><button class="remove" data-remove="${p.id}">Remove</button></div><span class="line-price">${money(p.price*x.qty)}</span></div>`}).join("");$("subtotal").textContent=money(state.cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.qty,0))}
function openCart(){$("drawer").classList.add("open");$("drawer").setAttribute("aria-hidden","false");$("overlay").hidden=false;requestAnimationFrame(()=>$("overlay").classList.add("visible"));document.body.classList.add("lock")}
function closeCart(){$("drawer").classList.remove("open");$("drawer").setAttribute("aria-hidden","true");$("overlay").classList.remove("visible");document.body.classList.remove("lock");setTimeout(()=>{if(!$("drawer").classList.contains("open"))$("overlay").hidden=true},260)}
function chooseCategory(category){state.category=category;document.querySelectorAll("[data-category]").forEach(b=>b.classList.toggle("selected",b.dataset.category===category));document.querySelectorAll("[data-filter]").forEach(a=>a.classList.toggle("active",a.dataset.filter===category));renderProducts()}
document.querySelectorAll("[data-category]").forEach(b=>b.addEventListener("click",()=>chooseCategory(b.dataset.category)));
document.querySelectorAll("[data-filter]").forEach(a=>a.addEventListener("click",()=>{chooseCategory(a.dataset.filter);$("nav").classList.remove("open")}));
$("products").addEventListener("click",e=>{const addBtn=e.target.closest("[data-add]"),fav=e.target.closest("[data-fav]");if(addBtn)add(Number(addBtn.dataset.add));if(fav){const id=Number(fav.dataset.fav);state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);renderProducts()}});
$("cart-items").addEventListener("click",e=>{const q=e.target.closest("[data-qty]"),r=e.target.closest("[data-remove]");if(q){const id=Number(q.dataset.qty),item=state.cart.find(x=>x.id===id);item.qty+=Number(q.dataset.delta);if(item.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);renderCart()}if(r){state.cart=state.cart.filter(x=>x.id!==Number(r.dataset.remove));renderCart()}});
$("sort").addEventListener("change",e=>{state.sort=e.target.value;renderProducts()});$("search").addEventListener("input",e=>{state.search=e.target.value.trim().toLowerCase();renderProducts()});
$("search-toggle").addEventListener("click",()=>{$("search-field").scrollIntoView({behavior:"smooth",block:"center"});$("search").focus()});
$("cart-open").addEventListener("click",openCart);$("cart-close").addEventListener("click",closeCart);$("overlay").addEventListener("click",closeCart);$("continue").addEventListener("click",closeCart);
$("checkout").addEventListener("click",()=>toast("Demo checkout — no payment was taken."));
$("reset").addEventListener("click",()=>{state.search="";state.sort="featured";$("search").value="";$("sort").value="featured";chooseCategory("all")});
$("menu-toggle").addEventListener("click",()=>$("nav").classList.toggle("open"));
$("newsletter").addEventListener("submit",e=>{e.preventDefault();$("newsletter-message").textContent="Thanks for your interest — signup is a demo.";e.currentTarget.reset()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeCart()});$("year").textContent=new Date().getFullYear();renderProducts();renderCart();
